### ISSUE TITLE
Answering a call with multiple strokes of the + key bugs the call.

### ISSUE THREAD

**Issue by Tomren3000** [Bitstackers/ReceptionistClient#102]
Answering an incoming call with multiple + keystrokes results in not being able  to hang up the call with the division key.

Also if the caller hangs up, the snom phone displays and maintains an open call, although the caller is hungup on their end.

**Comment by rostgaard** [comment]
Shouldbe(tm) fixed at
https://github.com/Bitstackers/ServerStack/commit/fea5f17414aabb48dbbda7be1b06be91daa211d0
