### ISSUE TITLE
Pause state for users

### ISSUE THREAD

**Issue by Tomren3000** [Bitstackers/ReceptionistClient#107]
Add pause state and toggle key-combo.

**Comment by rostgaard** [comment]
https://github.com/Bitstackers/ReceptionistClient/commit/eb627182c93815df89f4e9bcc612e3f5bf0a5320
https://github.com/Bitstackers/OpenReceptionFramework/commit/d830b4f706588df022232870c1a88fee63a63136
https://github.com/Bitstackers/ServerStack/commit/c06368974a7b33b436ffb4fa049ff8a5d489f5f8
