### ISSUE TITLE
Local extension does not show up in the received message (email).

### ISSUE THREAD

**Issue by Tomren3000** [Bitstackers/ReceptionistClient#110]

**Comment by rostgaard** [comment]
Fixed in bfcb9069ac63ffa988a4a2101f33a0f9015c8f8a
https://github.com/Bitstackers/ServerStack/commit/ec3d508808c59b09b126b74f5a83a09bf0f57992
https://github.com/Bitstackers/OpenReceptionFramework/commit/32305ba07ee3f2dd81c24dd887e9763d790951fe
