### ISSUE TITLE
contexthomeplus.companyother.company-other-body consumes all keyboard shortcuts

### ISSUE THREAD

**Issue by Tomren3000** [Bitstackers/ReceptionistClient#117]

**Comment by rostgaard** [comment]
The extradata for the reception is implemented as an iframe, so either we invent our own (markup based?) document format - or we teach our users that they have to click focus away before using shortcuts.

**Comment by ThomasLocke** [comment]
Since we now have a "miniwiki" widget that just consumes a markdown string, we can safely open external tools in a new browser tab/window and not care about this issue at all. No iframe hell! Win all over.  :)
