### ISSUE TITLE
Contact.phones should perhaps be a list of TelNum objects?

### ISSUE THREAD

**Issue by ThomasLocke** [Bitstackers/ReceptionistClient#127]
Currently it is just a map. Could we leverage the TelNum (in dummies.dart) class for this instead?

**Comment by rostgaard** [comment]
There is already a Model.PhoneNumber in the framework. I even found its way into the Contact server phone interface. Alas, not yet into the Contact model interface.
Expect patch soon-ish.

**Comment by rostgaard** [comment]
See referenced commit and close if it is an acceptable solution.

**Comment by ThomasLocke** [comment]
This looks great @rostgaard! Closing the issue.
