### ISSUE TITLE
Contact.endpoints is a List<Map> - should it be a List<Endpoint>? 

### ISSUE THREAD

**Issue by ThomasLocke** [Bitstackers/ReceptionistClient#128]
Also it seems to be missing cc/bcc information. Is this intentional?

**Comment by rostgaard** [comment]
Contact.endpoints should be updated to use the Model.MessageEndpoint.

The missing CC, BCC is indeed intentional. Every contact has a distributionList member which is a MessageRecipientList. Every MessageRecipient refers to a Contact (by id's) which has endpoints.

**Comment by rostgaard** [comment]
See referenced commit and close if it is an acceptable solution.

**Comment by ThomasLocke** [comment]
Using ORModel.MessageRecipientList.asMap now. Works.
