### ISSUE TITLE
Missing Controller.Notification.onDisconnect stream

### ISSUE THREAD

**Issue by ThomasLocke** [Bitstackers/ReceptionistClient#134]
I'd like to detect websocket disconnects, so the app can go into ERROR state if/when the websocket dies. Can I haz cookie @rostgaard? :D

**Comment by rostgaard** [comment]
Sure you can, but the cookies are mine, and mine alone.

**Comment by rostgaard** [comment]
The best way of going about this, would probably be to make a callback, as you only need one listener for this event.
Use onDone for the event stream for detecting notification socket disconnects.

https://github.com/Bitstackers/ReceptionistClient/blob/master/web/controller/controller-notification.dart#L81
