### ISSUE TITLE
Flaky user active/passive counters

### ISSUE THREAD

**Issue by ThomasLocke** [Bitstackers/ReceptionistClient#141]
Make the active/passive counters reliable.

State effect:
  Unknown => passive 
  Idle => active 
  Paused => passive
  Speaking => active
  Receiving => active
  HangingUp => active
  Transferring => active
  Dialing => active
  Parking => active
  Unparking => active
  LoggedOut => passive (or not even counted??)
  WrappingUp => active
  HandlingOffHook => active

NOTE: It is a problem that we have Idle and Paused here, as they are actually meta state. IRL you can be Paused while Speaking, and under such a circumstance you should not count among the active users.

Maybe we need to have both Model.UserCallState and Model.UserMetaState, or perhaps just expand on Model.UserState so it supports meta states?

**Comment by rostgaard** [comment]
I would suggest we introduce "busy" as extra informational state. Busy will then become all active non-idle states.
Idle should probably also be renamed to "ready", which makes more sense.
Paused should account for all passive states, and unknown is effectively also paused, as cannot assume that the agent is ready for calls.

So: Ready, Busy, Paused - or not counted (agents logged out or without a peer).
