### ISSUE TITLE
Priority lists should not have integer priority.

### ISSUE THREAD

**Issue by PedersenThomas** [Bitstackers/ReceptionistClient#75]
an item looks like 
[
  { 'priority': X1,
    'Value': Y1},
  { 'priority': X2,
    'Value': Y2},
...]

JSON preserv the order of a list, so just
[Y1, Y2, Y3]

**Comment by rostgaard** [comment]
Implemented in the serverstack and framework. The Client no longer uses the explicit priority lists.
