### ISSUE TITLE
Transfer action fails

### ISSUE THREAD

**Issue by Tomren3000** [Bitstackers/ReceptionistClient#78]
Forsøgte at omstille til Thomas' mobil, men da jeg trykkede på numerisk minus genvejs tast, blev kaldet ikke omstillet.

**Comment by rostgaard** [comment]
Lukker, da brugerfladen er blevet helt omskrevet siden rapporteringen. Åbn et nyt issue hvis problemet også eksisterer i den nye brugerflade.
