### ISSUE TITLE
Token timeout too fast

### ISSUE THREAD

**Issue by Tomren3000** [Bitstackers/ReceptionistClient#79]
If a receptionist is inactive for a prolonged period of time the interface becomes unresponsive without any visual indication of the token timeout.

The user must then manually clear the token from the location bar.

**Comment by rostgaard** [comment]
Changed the default timeout to 12 hours.
https://github.com/Bitstackers/ServerStack/commit/69689a1bceec7cfb06bb50b27a44b22fe48d94fc
